### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by warmachine-pixel** [hacker900123/XSS-Freak#6]
When given http://localhost/bWAPP/xss_get.php?firstname=Dipesh+Yadav&form=submit&lastname=d as target and payload.txt as wordlist it gives error.See the picture.
![image](https://user-images.githubusercontent.com/59498388/71761513-e88dd900-2e90-11ea-9024-1a683076461e.png)
![image](https://user-images.githubusercontent.com/59498388/71761517-f3486e00-2e90-11ea-85f8-25a93d47b893.png)
(THERE IS NO SUPPORT FOR POST REQUEST TOO)

**Comment by Ded-X** [comment]
For me, the script won't even work at all. Should I try this on Kali Linux or Parrot Linux?
![image](https://user-images.githubusercontent.com/52713342/74485880-c329bd00-4e89-11ea-85f1-3105ebeab392.png)

**Comment by rayabee** [comment]
Same issue here:

>> [+] Give Me A Target To Destroy                                                                                                                                                                                                         
>> [?] Enter Target: http://testphp.vulnweb.com                                                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                                                                                         
  File "XSS-Freak.py", line 33, in <module>                                                                                                                                                                                                
    host = input(Fore.CYAN + Style.BRIGHT + ">> [?] Enter Target: ")                                                                                                                                                                       
  File "<string>", line 1                                                                                                                                                                                                                  
    http://testphp.vulnweb.com                                                                                                                                                                                                             
        ^                                                                                                                                                                                                                                  
SyntaxError: invalid syntax

**Comment by PR0PH3CY33** [comment]
Sorry for the late response but in a couple of days i will do a whole remake of this tool which will work even more efficiently.
