### ISSUE TITLE
IndexError: string index out of range for blanks `href` attr

### ISSUE THREAD

**Issue by Jul10l1r4** [hacker900123/XSS-Freak#8]
Error: `line 26`
Type error: `IndexError`

I change the except for IndexError and received the value invalid href:
```
<a class="noticias-ler-mais" href="">Ler mais <i class="fa fa-angle-right"></i></a> fudeu: string index out of range
<a class="noticias-ler-mais" href="">Ler mais <i class="fa fa-angle-right"></i></a> fudeu: string index out of range
<a class="noticias-ler-mais" href="">Ler mais <i class="fa fa-angle-right"></i></a> fudeu: string index out of range
<a class="noticias-ler-mais" href="">Ler mais <i class="fa fa-angle-right"></i></a> fudeu: string index out of range
Traceback (most recent call last):
  File "XSS-Freak.py", line 98, in <module>
    find_links()
  File "XSS-Freak.py", line 80, in find_links
    if(i['href'][0] != "/" and i['href'][-1] == "/" and i['href'].startswith("https") == False and i['href'].startswith("http") == False):
IndexError: string index out of range
```

**Comment by AlekKras** [comment]
yeah, I couldn't figure out how to solve this issue just yet. Having the same problem here using the tool.

**Comment by PR0PH3CY33** [comment]
Sorry for the late response but in a couple of days i will do a better remake of this tool which the user will have more control.
